import { Trade, MissedTrade, DailyNote, TradingRule } from './types';

export const INITIAL_TRADES: Trade[] = [
  {
    id: "tr-101",
    symbol: "XAU/USD",
    assetClass: "commodities",
    direction: "LONG",
    status: "WIN",
    entryDate: "2026-09-16",
    entryTime: "08:45",
    exitDate: "2026-09-16",
    exitTime: "11:20",
    entryPrice: 2584.50,
    exitPrice: 2602.80,
    stopLoss: 2577.00,
    takeProfit: 2605.00,
    size: 1.5,
    riskAmount: 1125,
    netPnL: 2745.00,
    rMultiple: 2.44,
    returnPercent: 12.2,
    fees: 18.00,
    setup: "Asian Range Liquidity Grab",
    session: "London",
    timeframe: "5m",
    mistakes: [],
    emotions: {
      pre: "Disciplined",
      during: "Patient",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Perfect sweep of Asian low during London open with massive bullish displacement. Waited for 5m FVG retest before executing.",
    whatWentWell: "Patience on entry, adhered strictly to the 1.5R partial TP rule.",
    whatToImprove: "Could have left a 10% runner for higher timeframe target at 2610.",
    chartUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80",
    account: "Main Funded 100k"
  },
  {
    id: "tr-102",
    symbol: "NQ (Nasdaq)",
    assetClass: "indices",
    direction: "SHORT",
    status: "LOSS",
    entryDate: "2026-09-15",
    entryTime: "09:40",
    exitDate: "2026-09-15",
    exitTime: "09:52",
    entryPrice: 19840.25,
    exitPrice: 19885.00,
    stopLoss: 19875.00,
    takeProfit: 19740.00,
    size: 2.0,
    riskAmount: 1400,
    netPnL: -1790.00,
    rMultiple: -1.28,
    returnPercent: -7.9,
    fees: 14.50,
    setup: "Breakout & Retest",
    session: "New York",
    timeframe: "1m",
    mistakes: ["FOMO / Chased Entry", "Moved Stop Loss Early"],
    emotions: {
      pre: "FOMO",
      during: "Stressed",
      post: "Frustrated",
    },
    followedPlan: false,
    notes: "Market opened very fast and I entered without waiting for candle close. When price pushed against me, I nudged the stop by 10 points thinking it was just a wick.",
    whatWentWell: "Recognized the breach and killed the trade before full catastrophic loss.",
    whatToImprove: "NEVER move stop loss away from market. Accept the initial 1R risk.",
    chartUrl: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80",
    account: "Main Funded 100k"
  },
  {
    id: "tr-103",
    symbol: "BTC/USDT",
    assetClass: "crypto",
    direction: "LONG",
    status: "WIN",
    entryDate: "2026-09-14",
    entryTime: "14:15",
    exitDate: "2026-09-14",
    exitTime: "18:30",
    entryPrice: 62450.00,
    exitPrice: 63980.00,
    stopLoss: 61850.00,
    takeProfit: 64200.00,
    size: 0.8,
    riskAmount: 480,
    netPnL: 1224.00,
    rMultiple: 2.55,
    returnPercent: 15.3,
    fees: 9.80,
    setup: "Orderblock Demand",
    session: "New York",
    timeframe: "15m",
    mistakes: [],
    emotions: {
      pre: "Calm",
      during: "Patient",
      post: "Disciplined",
    },
    followedPlan: true,
    notes: "Higher timeframe daily bullish orderblock held firmly on 4H. Drop into 15m showed clean change of character and retest.",
    whatWentWell: "Calm execution without second guessing.",
    whatToImprove: "Execution was solid.",
    account: "Apex Prop"
  },
  {
    id: "tr-104",
    symbol: "EUR/USD",
    assetClass: "forex",
    direction: "SHORT",
    status: "WIN",
    entryDate: "2026-09-12",
    entryTime: "07:30",
    exitDate: "2026-09-12",
    exitTime: "10:15",
    entryPrice: 1.0920,
    exitPrice: 1.0865,
    stopLoss: 1.0945,
    takeProfit: 1.0860,
    size: 3.0,
    riskAmount: 750,
    netPnL: 1650.00,
    rMultiple: 2.20,
    returnPercent: 11.0,
    fees: 12.00,
    setup: "ICT Fair Value Gap + Sweep",
    session: "London",
    timeframe: "15m",
    mistakes: [],
    emotions: {
      pre: "Confident",
      during: "Calm",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Clean London sweep of Asian high followed by institutional displacement down into New York pre-market liquidity pool.",
    whatWentWell: "Waited patiently for candle closure below 1.0910 before entry.",
    whatToImprove: "Trailing stop could have been adjusted closer to lock in +2R sooner.",
    account: "Main Funded 100k"
  },
  {
    id: "tr-105",
    symbol: "NVDA",
    assetClass: "stocks",
    direction: "LONG",
    status: "WIN",
    entryDate: "2026-09-11",
    entryTime: "10:00",
    exitDate: "2026-09-11",
    exitTime: "14:45",
    entryPrice: 118.50,
    exitPrice: 124.20,
    stopLoss: 116.00,
    takeProfit: 125.00,
    size: 200,
    riskAmount: 500,
    netPnL: 1140.00,
    rMultiple: 2.28,
    returnPercent: 14.2,
    fees: 5.00,
    setup: "VWAP Mean Reversion",
    session: "New York",
    timeframe: "5m",
    mistakes: [],
    emotions: {
      pre: "Calm",
      during: "Disciplined",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Deep morning pullback to VWAP + 200 SMA on 5min chart during semiconductor sector strength.",
    whatWentWell: "Clear risk-defined entry. Exited exactly at predetermined resistance.",
    account: "Equities Margin"
  },
  {
    id: "tr-106",
    symbol: "GBP/JPY",
    assetClass: "forex",
    direction: "LONG",
    status: "LOSS",
    entryDate: "2026-09-10",
    entryTime: "04:10",
    exitDate: "2026-09-10",
    exitTime: "05:00",
    entryPrice: 188.40,
    exitPrice: 187.95,
    stopLoss: 187.95,
    takeProfit: 189.50,
    size: 2.0,
    riskAmount: 900,
    netPnL: -900.00,
    rMultiple: -1.00,
    returnPercent: -6.0,
    fees: 16.00,
    setup: "20 EMA Trend Pullback",
    session: "Asia",
    timeframe: "15m",
    mistakes: ["Traded Outside Optimal Session"],
    emotions: {
      pre: "Rushed",
      during: "Anxious",
      post: "Frustrated",
    },
    followedPlan: false,
    notes: "Traded during Asian session when volume is typically choppy for GBP cross. Spread widened on Japanese news.",
    whatWentWell: "Honored stop loss strictly without moving it.",
    whatToImprove: "Stick to London and New York sessions for GBP pairs.",
    account: "Main Funded 100k"
  },
  {
    id: "tr-107",
    symbol: "ES (S&P 500)",
    assetClass: "indices",
    direction: "SHORT",
    status: "WIN",
    entryDate: "2026-09-09",
    entryTime: "11:30",
    exitDate: "2026-09-09",
    exitTime: "13:00",
    entryPrice: 5625.50,
    exitPrice: 5602.00,
    stopLoss: 5635.00,
    takeProfit: 5595.00,
    size: 2.0,
    riskAmount: 950,
    netPnL: 2350.00,
    rMultiple: 2.47,
    returnPercent: 15.6,
    fees: 15.00,
    setup: "ICT Fair Value Gap + Sweep",
    session: "New York",
    timeframe: "5m",
    mistakes: [],
    emotions: {
      pre: "Confident",
      during: "Patient",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Failed to take out previous day high, formed clear bearish divergence on momentum indicators.",
    whatWentWell: "Patient entry on the 5m mitigation block.",
    account: "Main Funded 100k"
  },
  {
    id: "tr-108",
    symbol: "SOL/USDT",
    assetClass: "crypto",
    direction: "LONG",
    status: "WIN",
    entryDate: "2026-09-08",
    entryTime: "16:40",
    exitDate: "2026-09-08",
    exitTime: "21:10",
    entryPrice: 132.50,
    exitPrice: 141.20,
    stopLoss: 129.00,
    takeProfit: 142.00,
    size: 150,
    riskAmount: 525,
    netPnL: 1305.00,
    rMultiple: 2.48,
    returnPercent: 16.5,
    fees: 8.50,
    setup: "Breakout & Retest",
    session: "New York",
    timeframe: "1h",
    mistakes: [],
    emotions: {
      pre: "Disciplined",
      during: "Calm",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Consolidation breakout above key $130 psychological resistance with strong spot volume volume confirmation.",
    whatWentWell: "Let the trade breathe on 1H timeframe without micro-managing 1min candles.",
    account: "Apex Prop"
  },
  {
    id: "tr-109",
    symbol: "XAU/USD",
    assetClass: "commodities",
    direction: "LONG",
    status: "LOSS",
    entryDate: "2026-09-05",
    entryTime: "13:15",
    exitDate: "2026-09-05",
    exitTime: "13:30",
    entryPrice: 2518.00,
    exitPrice: 2508.50,
    stopLoss: 2510.00,
    takeProfit: 2540.00,
    size: 2.0,
    riskAmount: 1600,
    netPnL: -1900.00,
    rMultiple: -1.18,
    returnPercent: -8.5,
    fees: 20.00,
    setup: "Asian Range Liquidity Grab",
    session: "New York",
    timeframe: "5m",
    mistakes: ["Traded High-Impact News", "Overleveraged Position"],
    emotions: {
      pre: "Greedy",
      during: "Stressed",
      post: "Revengeful",
    },
    followedPlan: false,
    notes: "Jumped in 15 minutes before US Non-Farm Payroll / jobs release. Slippage hit stop loss further down.",
    whatWentWell: "None. Direct violation of pre-defined rule #3 (No trading 30m before Tier-1 red folder news).",
    whatToImprove: "Strictly set an alarm before economic data releases and close or flatten terminal.",
    account: "Main Funded 100k"
  },
  {
    id: "tr-110",
    symbol: "TSLA",
    assetClass: "stocks",
    direction: "SHORT",
    status: "BE",
    entryDate: "2026-09-04",
    entryTime: "10:10",
    exitDate: "2026-09-04",
    exitTime: "11:50",
    entryPrice: 220.00,
    exitPrice: 219.90,
    stopLoss: 224.00,
    takeProfit: 210.00,
    size: 100,
    riskAmount: 400,
    netPnL: 10.00,
    rMultiple: 0.02,
    returnPercent: 0.2,
    fees: 3.50,
    setup: "VWAP Mean Reversion",
    session: "New York",
    timeframe: "15m",
    mistakes: ["Exited Before Target"],
    emotions: {
      pre: "Hesitant",
      during: "Anxious",
      post: "Regretful",
    },
    followedPlan: false,
    notes: "Moved stop to breakeven prematurely at +0.7R. Got tagged out right before the big flush to $212.",
    whatWentWell: "Protected capital, but did not allow the probability edge to play out.",
    whatToImprove: "Only move stop to BE after +1.5R target is reached.",
    account: "Equities Margin"
  },
  {
    id: "tr-111",
    symbol: "EUR/USD",
    assetClass: "forex",
    direction: "LONG",
    status: "WIN",
    entryDate: "2026-09-03",
    entryTime: "08:15",
    exitDate: "2026-09-03",
    exitTime: "11:00",
    entryPrice: 1.0830,
    exitPrice: 1.0890,
    stopLoss: 1.0805,
    takeProfit: 1.0895,
    size: 2.5,
    riskAmount: 625,
    netPnL: 1500.00,
    rMultiple: 2.40,
    returnPercent: 12.0,
    fees: 11.00,
    setup: "ICT Fair Value Gap + Sweep",
    session: "London",
    timeframe: "15m",
    mistakes: [],
    emotions: {
      pre: "Disciplined",
      during: "Patient",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Textbook London open expansion targeting buy-side liquidity above London prior day high.",
    whatWentWell: "Held all the way into the London/NY overlap.",
    account: "Main Funded 100k"
  },
  {
    id: "tr-112",
    symbol: "NQ (Nasdaq)",
    assetClass: "indices",
    direction: "LONG",
    status: "WIN",
    entryDate: "2026-09-02",
    entryTime: "14:00",
    exitDate: "2026-09-02",
    exitTime: "15:45",
    entryPrice: 19520.00,
    exitPrice: 19680.00,
    stopLoss: 19460.00,
    takeProfit: 19700.00,
    size: 1.5,
    riskAmount: 900,
    netPnL: 2400.00,
    rMultiple: 2.66,
    returnPercent: 16.0,
    fees: 12.50,
    setup: "Breakout & Retest",
    session: "New York",
    timeframe: "15m",
    mistakes: [],
    emotions: {
      pre: "Calm",
      during: "Disciplined",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Fed speaker was dovish, tech rallied off afternoon support shelf. Clean continuation setup.",
    whatWentWell: "Waited 15 minutes after remarks ended before jumping into momentum.",
    account: "Main Funded 100k"
  },
  {
    id: "tr-113",
    symbol: "BTC/USDT",
    assetClass: "crypto",
    direction: "SHORT",
    status: "LOSS",
    entryDate: "2026-08-30",
    entryTime: "19:00",
    exitDate: "2026-08-30",
    exitTime: "20:10",
    entryPrice: 60100.00,
    exitPrice: 60950.00,
    stopLoss: 60800.00,
    takeProfit: 58500.00,
    size: 0.7,
    riskAmount: 490,
    netPnL: -595.00,
    rMultiple: -1.21,
    returnPercent: -7.2,
    fees: 8.00,
    setup: "Orderblock Demand",
    session: "Overnight",
    timeframe: "30m",
    mistakes: ["Revenge Trade After Loss"],
    emotions: {
      pre: "Revengeful",
      during: "Stressed",
      post: "Frustrated",
    },
    followedPlan: false,
    notes: "Attempted to short crypto over the weekend during thin liquidity to make back earlier intraday loss.",
    whatWentWell: "Nothing. Weekend chop is toxic.",
    whatToImprove: "Weekend rule: Zero active trading on weekends. Rest and recharge.",
    account: "Apex Prop"
  },
  {
    id: "tr-114",
    symbol: "XAU/USD",
    assetClass: "commodities",
    direction: "SHORT",
    status: "WIN",
    entryDate: "2026-08-28",
    entryTime: "09:10",
    exitDate: "2026-08-28",
    exitTime: "11:40",
    entryPrice: 2530.00,
    exitPrice: 2505.00,
    stopLoss: 2540.00,
    takeProfit: 2500.00,
    size: 1.2,
    riskAmount: 1200,
    netPnL: 3000.00,
    rMultiple: 2.50,
    returnPercent: 15.0,
    fees: 18.00,
    setup: "Asian Range Liquidity Grab",
    session: "London",
    timeframe: "15m",
    mistakes: [],
    emotions: {
      pre: "Confident",
      during: "Patient",
      post: "Satisfied",
    },
    followedPlan: true,
    notes: "Classic institutional liquidity sweep above 2530 previous high, followed by aggressive selloff into daily orderblock.",
    whatWentWell: "Execution was patient, TP was hit cleanly.",
    account: "Main Funded 100k"
  }
];

export const INITIAL_MISSED_TRADES: MissedTrade[] = [
  {
    id: "mt-01",
    date: "2026-09-16",
    time: "14:30",
    symbol: "NQ (Nasdaq)",
    assetClass: "indices",
    direction: "LONG",
    setup: "ICT Fair Value Gap + Sweep",
    plannedEntry: 19820,
    stopLoss: 19780,
    plannedExit: 19940,
    potentialR: 3.0,
    potentialPnL: 2400,
    reason: "Fear of Loss",
    notes: "Had taken a loss on NQ the day before, so when the exact A+ setup appeared, I froze and hesitated for 2 minutes. The train left the station.",
    chartUrl: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80"
  },
  {
    id: "mt-02",
    date: "2026-09-13",
    time: "08:15",
    symbol: "EUR/USD",
    assetClass: "forex",
    direction: "SHORT",
    setup: "Asian Range Liquidity Grab",
    plannedEntry: 1.0940,
    stopLoss: 1.0960,
    plannedExit: 1.0880,
    potentialR: 3.0,
    potentialPnL: 1800,
    reason: "Hesitation",
    notes: "Second-guessed the entry because Dollar index had a choppy candle. It subsequently dropped 60 pips without pullback.",
  },
  {
    id: "mt-03",
    date: "2026-09-07",
    time: "15:00",
    symbol: "BTC/USDT",
    assetClass: "crypto",
    direction: "LONG",
    setup: "Orderblock Demand",
    plannedEntry: 61200,
    stopLoss: 60500,
    plannedExit: 63500,
    potentialR: 3.28,
    potentialPnL: 2300,
    reason: "Away from Desk",
    notes: "Left the desk to grab coffee right when limit order was 5 dollars away from filling.",
  }
];

export const INITIAL_DAILY_NOTES: DailyNote[] = [
  {
    id: "dn-01",
    date: "2026-09-16",
    rating: 5,
    marketCondition: "Trending Bullish",
    preMarketNotes: "High focus today. Key news is US retail sales at 8:30am NY. Will wait until after data release before initiating any new index trades.",
    postMarketNotes: "Executed Gold flawlessly on London open. Rest of the day was disciplined. Did not overtrade during the late NY session.",
    followedRules: true,
    keyLesson: "Execution quality directly follows emotional calmness during the first 30 minutes of market open."
  },
  {
    id: "dn-02",
    date: "2026-09-15",
    rating: 2,
    marketCondition: "High Volatility",
    preMarketNotes: "Feeling slightly rushed this morning due to traffic. Need to take deep breaths and not force anything.",
    postMarketNotes: "Gave in to FOMO on NQ right at open and violated rule #2 by nudging stop loss. Lost $1,790. Immediate penalty: stopped trading for the remainder of the day.",
    followedRules: false,
    keyLesson: "If feeling hurried before open, DO NOT trade market open. Sit on hands until 10:00 AM."
  }
];

export const INITIAL_RULES: TradingRule[] = [
  {
    id: "r-1",
    title: "Maximum 1.5% Risk Per Trade",
    category: "Risk",
    description: "Never risk more than $1,500 (1.5% of $100k account) on any single setup under any circumstance.",
    isActive: true
  },
  {
    id: "r-2",
    title: "Never Move Stop Loss Away From Market",
    category: "Risk",
    description: "Once placed, the stop loss is non-negotiable. Only moving towards profit (trailing) is permitted.",
    isActive: true
  },
  {
    id: "r-3",
    title: "Max 2 Losses Per Day Circuit Breaker",
    category: "Psychology",
    description: "If two consecutive trades hit stop loss in a single trading day, shut down the platform immediately.",
    isActive: true
  },
  {
    id: "r-4",
    title: "Wait For 5m Candle Close Before Entry",
    category: "Execution",
    description: "No entering on intra-candle impulses. Confirmation on candle close is mandatory.",
    isActive: true
  },
  {
    id: "r-5",
    title: "No Weekend Crypto Trading",
    category: "Routine",
    description: "Crypto weekend chop has negative expectancy. Review journals on weekends instead.",
    isActive: true
  }
];
